name: Financial_Crimes
description: Combine wire transfers and various watchlists and enrich with rules to
  calculate a risk score to identify potentially nefarious transactions
version: '10.4'
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: financialcrimes
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-02-14 17:00:07'
pipelines:
  pipelines/pipe_financial_crimes:
    name: pipe_financial_crimes
    description: This codebase provides a solution for detecting financial crimes
      by analyzing wire transfer transactions. It reads in data from multiple sources,
      including a wire transfer table, individual watchlist, and country watchlist.
      It then joins these data sources to create a comprehensive view of each transaction,
      including the full name of the sender and receiver, their respective banks and
      account numbers, originating and destination countries, and transaction amount.
      The code then calculates a risk score for each transaction based on various
      factors, including whether the sender or receiver is on the watchlist, whether
      the originating or destination country is on the watchlist, and the transaction
      amount. Finally, the code sorts the transactions by risk score, allowing for
      easy identification of high-risk transactions that may require further investigation.
      This solution could be used by financial institutions to proactively detect
      and prevent financial crimes such as money laundering and terrorist financing.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 17:00:07'
    datasets:
      inputs:
      - datasets/ds_country_watchlist
      - datasets/ds_person_watchlist
      - datasets/table_wire_transfer
      outputs:
      - datasets/all_scored_transx
      - datasets/flagged_transactions
      - datasets/table_all_transx_scored
    subgraphs:
    - subgraphs/risk_scoring
    dependencies: {}
datasets:
  datasets/ds_country_watchlist:
    name: ds_country_watchlist
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-14 17:39:36'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 17:39:36'
  datasets/ds_person_watchlist:
    name: ds_person_watchlist
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-14 18:36:45'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 18:36:45'
  datasets/flagged_transactions:
    name: flagged_transactions
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-15 21:02:29'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-15 21:02:29'
  datasets/all_scored_transx:
    name: all_scored_transx
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-15 21:11:31'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-15 21:11:31'
  datasets/table_wire_transfer:
    name: table_wire_transfer
    description: The 'wire_transfer' table contains data related to financial crimes
      involving wire transfers. It includes information about the transaction such
      as the sender and recipient, the originating and destination countries, and
      the amount of the transaction. This data can be used to track patterns in illegal
      wire transfers, identify suspicious activities, and assist in investigations
      into financial crime.
    author: bobw@prophecy.io
    createdAt: '2024-02-21 15:47:42'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-21 15:47:42'
  datasets/table_all_transx_scored:
    name: table_all_transx_scored
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-21 15:53:12'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-21 15:53:12'
templates: {}
jobs:
  jobs/job_fin_crimes:
    name: job_fin_crimes
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 1 ? *
    timeout: null
    alerting:
      emails: bobw@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/pipe_financial_crimes
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-20 18:22:09'
    author: bobw@prophecy.io
  jobs/job_fincrimes_airflow:
    name: job_fincrimes_airflow
    description: ''
    fabricUID: 9770
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pipe_financial_crimes
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-20 19:49:37'
    author: bobw@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-14 17:00:07'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs:
  subgraphs/risk_scoring:
    name: risk_scoring
    description: Sub transformations the score wire transfers for potentially nefarious
      purposes
    author: bobw@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2024-02-20 19:16:52'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-04-05T17:37:16.315363Z'
  name: plibMaven
  version: 7.1.83
  id: '1942385491'
  createdAt: '2024-04-05T17:37:16.315258Z'
- type: plibPypi
  modifiedAt: '2024-04-05T17:37:16.315531Z'
  name: plibPypi
  version: 1.8.13
  id: '1469039237'
  createdAt: '2024-04-05T17:37:16.315462Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-04 16:20:45'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-04 16:20:48'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
